name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ clang-tidy cppcheck

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build
        run: cmake --build build -j

      - name: Run cppcheck
        run: cppcheck --project=build/compile_commands.json --inline-suppr --error-exitcode=1

      - name: Tests
        run: ctest --test-dir build --output-on-failure